import turtle
t = turtle.Turtle()
t.fillcolor("orange")
t.begin_fill()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)
t.end_fill()
turtle.done()
